### ISSUE TITLE
would like to use your plugin BUT

### ISSUE THREAD

**Issue by dpalic** [fredsdc/redmine_user_management#1]
do not understand how to use it your plugin

are there screenshots and a description how to use the plugin?

My expectations are:
Allow non administrator users to register totally new users and to assign them some default groups.
But sadly not clear how to do it

tried it with ubuntu 18.04 and redmine 3.4.4

**Comment by fredsdc** [comment]
I have added some pictures with explanations to the "doc" directory.
This plugin was created for redmine 4, I don't know if it works with redmine 3.
