### ISSUE TITLE
Redmine user management Plugin Users Tab Error

### ISSUE THREAD

**Issue by jcdelacernajr** [fredsdc/redmine_user_management#3]
Hello Sir,

Testing the users tab and its function.
I tried the save button and  its seems there is a bug for I did not receive  the email notification for my generated password.

![1](https://user-images.githubusercontent.com/56627340/127986433-aa82a49f-2514-40c9-ba84-6a45cbee7d46.jpg)

Here's the production log

```
Started PATCH "/user_managements/16" for 127.0.0.1 at 2021-08-03 16:02:34 +0800
Processing by UserManagementsController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"4mjQNEAiHb9tTKbg186fPiLYLFt1kQRdpOlMF4FgoSjLNYKFCf5x+NPZllT0C0F75DHspjiooUZ6fBWoMOFF5A==", "user"=>{"login"=>"janthon", "firstname"=>"jay", "lastname"=>"cruz", "mail"=>"janthon@gmail.com", "generate_password"=>"[FILTERED]", "must_change_passwd"=>"0", "status"=>"1"}, "commit"=>"Save", "id"=>"16"}
  Current user: jbuser (id=5)
Completed 500 Internal Server Error in 15ms (ActiveRecord: 5.2ms)
  
TypeError (no implicit conversion of nil into Array):
  
plugins/redmine_user_management/app/controllers/user_managements_controller.rb:135:in `&'
plugins/redmine_user_management/app/controllers/user_managements_controller.rb:135:in `what_to_update'
plugins/redmine_user_management/app/controllers/user_managements_controller.rb:55:in `update'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Pls. can you check this error

BTW The plugin was nice and it's very simple. 

Note: But my email configuration was fine because I am receiving email when I do a forgot password.

Thanks.

**Comment by fredsdc** [comment]
Fixed, please test:
git pull
RAILS_ENV=production bundle exec rake redmine:plugins:migrate NAME=redmine_user_management
touch tmp/restart.txt
