### ISSUE TITLE
E-Mails sent to user do not contain TO field

### ISSUE THREAD

**Issue by dpalic** [fredsdc/redmine_user_management#6]
The received E-Mails to the user do not contain the TO header field of the e-mail.

can you point me to the location where to change it? would deliver a PR for it, if you are interested to change it accordingly having TO header filed set?

**Comment by fredsdc** [comment]
Hi. I think this plugin notifies new users the same way as when creating a new user in Administration > Users > New user.

redmine_user_management/app/controllers/user_managements_controller.rb, line 41 calls function deliver_account_information from Mailer model.

It's the same way as in Redmine's app/controllers/users_controller.rb, around line 116

The mailing function is defined in Redmine's app/models/mailer.rb, around line 353
