### ISSUE TITLE
Make 'Must change password at next logon' checked as default

### ISSUE THREAD

**Issue by dpalic** [fredsdc/redmine_user_management#7]
IMHO 
Must change password at next logon
should be checked for the cases that the user is getting freshly created, password generated.
The user should create its own hidden password, which is not shared via email after the logged in successfully the first time

**Comment by fredsdc** [comment]
This plugin mimics somehow Redmine's behaviour in Administration > User > New user.

When you click there, this option default is unchecked (at least in Redmine 4.X)

In Redmine > Configuration > Users, there is no configuration for this checkbox default behaviour.

Where to change the default behaviour:
app/views/users/_form.html.erb:39
plugins/redmine_user_management/app/views/user_managements/_form.html.erb:30
